### ISSUE TITLE
Cover sizing with vw/vh

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#422]
Despite #413 and #414 this one doesn't seem to be working yet.

https://dbnl.org/tekst/lapi001goet01_01/
https://dbnl.org/tekst/lapi001goet01_01/ebook/lapi001goet01_01.epub

**Comment by poire-z** [comment]
Where do you see any wv/wh ?
```html
<div class="cover">
<img src="images/lapi001goet01_01_tpg.gif" alt="cover"/></div></div>
```
```css
div.cover {text-align: center;}
div.cover img { width: auto; height: 100%;}
```

heights in % (of container height, that we don't know yet when we render the inner thing) are not supported.

Change this `div.cover img { width: auto; height: 100%;}`
to `div.cover img { width: auto; height: 100vh;}`, and it works.
