### ISSUE TITLE
Add list type attributes to default stylesheet

### ISSUE THREAD

**Issue by Frenzie** [koreader/crengine#480]
Lists have a type attribute that apparently currently isn't taken into account. It can easily be supported like this:

```css
ol[type="a"] {
 list-style-type: lower-alpha;
}
ol[type="A"] {
 list-style-type: upper-alpha;
}
/* etc. */
```

See https://www.mobileread.com/forums/showthread.php?p=4224519

### For OL

    a for lowercase letters
    A for uppercase letters
    i for lowercase Roman numerals
    I for uppercase Roman numerals
    1 for numbers (default)

### For UL
    circle
    disc
    square
