### ISSUE TITLE
Support drop caps

### ISSUE THREAD

**Issue by arjpar** [koreader/crengine#600]
ie
```css
p:first-child:first-letter {
  color: #903;
  float: left;
  font-family: Georgia;
  font-size: 75px;
  line-height: 60px;
  padding-top: 4px;
  padding-right: 8px;
  padding-left: 3px;
}
/* or */

p:first-child:first-letter {
  color: #903; 
  font-family: Georgia;
  initial-letter: 2;
}
```

Drop caps rendered in KOReader:
![E55A25DA-F8F9-4495-83A3-6834BCFED3C3_1_102_o](https://github.com/user-attachments/assets/e6d5dadf-44f8-4d58-8436-a9c3c419af27)

Drop caps properly rendered:
![image](https://github.com/user-attachments/assets/bf57c128-e43a-487e-ae1d-0f064e61e81a)
